# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'lo.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 500)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(180, 150, 91, 51))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(180, 230, 91, 51))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.acc_lo = QtWidgets.QTextEdit(self.centralwidget)
        self.acc_lo.setGeometry(QtCore.QRect(300, 150, 241, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.acc_lo.setFont(font)
        self.acc_lo.setObjectName("acc_lo")
        self.pas_lo = QtWidgets.QLineEdit(self.centralwidget)
        self.pas_lo.setGeometry(QtCore.QRect(300, 230, 241, 51))
        self.pas_lo.setObjectName("pas_lo")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(260, 20, 331, 61))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.log = QtWidgets.QPushButton(self.centralwidget)
        self.log.setGeometry(QtCore.QRect(470, 360, 131, 51))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.log.setFont(font)
        self.log.setObjectName("log")
        self.can = QtWidgets.QPushButton(self.centralwidget)
        self.can.setGeometry(QtCore.QRect(630, 360, 121, 51))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.can.setFont(font)
        self.can.setObjectName("can")
        self.res = QtWidgets.QPushButton(self.centralwidget)
        self.res.setGeometry(QtCore.QRect(20, 350, 121, 71))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.res.setFont(font)
        self.res.setObjectName("res")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(310, 300, 291, 41))
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 25))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "帳號"))
        self.label_2.setText(_translate("MainWindow", "密碼"))
        self.label_3.setText(_translate("MainWindow", "歡迎使用積木復健系統"))
        self.log.setText(_translate("MainWindow", "登入"))
        self.can.setText(_translate("MainWindow", "取消"))
        self.res.setText(_translate("MainWindow", "註冊頁面"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
